TERMUX_PKG_HOMEPAGE=https://git.xfce.org/xfce/libxfce4util/tree/README
TERMUX_PKG_DESCRIPTION="The libxfce4util package is a basic utility library for the Xfce desktop environment."
_MAJOR_VERSION=4.12
TERMUX_PKG_VERSION=${_MAJOR_VERSION}.1
TERMUX_PKG_MAINTAINER="lokesh @hax4us"
TERMUX_PKG_DEPENDS="glib-2.0"
#TERMUX_PKG_BUILD_DEPENDS="pkg-config, gettext"
TERMUX_PKG_SHA256=876bdefa2e13cbf68b626b2158892fb93e824e1ef59cf951123a96cefbc8881d
TERMUX_PKG_SRCURL=http://archive.xfce.org/src/xfce/libxfce4util/${_MAJOR_VERSION}/libxfce4util-${TERMUX_PKG_VERSION}.tar.bz2
#TERMUX_PKG_EXTRA_CONFIGURE_ARGS=" --disable-nls"
